"""End-to-end tests for README examples.

These tests ensure that all code examples in the README work correctly.
"""
import numpy as np
import pytest

from python_prtree import PRTree2D


def test_basic_example():
    """Test README basic example.."""
    idxes = np.array([1, 2])

    # rects is a list of (xmin, ymin, xmax, ymax)
    rects = np.array([[0.0, 0.0, 1.0, 0.5], [1.0, 1.5, 1.2, 3.0]])

    prtree = PRTree2D(idxes, rects)

    # batch query
    q = np.array([[0.5, 0.2, 0.6, 0.3], [0.8, 0.5, 1.5, 3.5]])
    result = prtree.batch_query(q)
    assert result == [[1], [1, 2]]

    # You can insert an additional rectangle by insert method,
    prtree.insert(3, np.array([1.0, 1.0, 2.0, 2.0]))
    q = np.array([[0.5, 0.2, 0.6, 0.3], [0.8, 0.5, 1.5, 3.5]])
    result = prtree.batch_query(q)
    assert result == [[1], [1, 2, 3]]

    # Plus, you can erase by an index.
    prtree.erase(2)
    result = prtree.batch_query(q)
    assert result == [[1], [1, 3]]

    # Non-batch query is also supported.
    assert prtree.query([0.5, 0.5, 1.0, 1.0]) == [1, 3]

    # Point query is also supported.
    assert prtree.query([0.5, 0.5]) == [1]
    assert prtree.query(0.5, 0.5) == [1]

    # Find all pairs of intersecting rectangles
    # Box 1: [0.0, 0.0, 1.0, 0.5], Box 3: [1.0, 1.0, 2.0, 2.0]
    # No intersection: Box 1 ymax=0.5 < Box 3 ymin=1.0 (no Y overlap)
    pairs = prtree.query_intersections()
    assert pairs.tolist() == []


def test_object_example():
    """Test README object example.."""
    objs = [{"name": "foo"}, (1, 2, 3)]  # must NOT be unique but pickable
    rects = np.array([[0.0, 0.0, 1.0, 0.5], [1.0, 1.5, 1.2, 3.0]])

    prtree = PRTree2D()
    for obj, rect in zip(objs, rects):
        prtree.insert(bb=rect, obj=obj)

    # returns indexes generated by incremental rule.
    result = prtree.query((0, 0, 1, 1))
    assert result == [1]

    # returns objects when you specify the keyword argument return_obj=True
    result = prtree.query((0, 0, 1, 1), return_obj=True)
    assert result == [{"name": "foo"}]


def test_batch_vs_single_query_example():
    """Test README batch query vs single query example.."""
    idxes = np.array([1, 2])
    rects = np.array([[0.0, 0.0, 1.0, 0.5], [1.0, 1.5, 1.2, 3.0]])
    prtree = PRTree2D(idxes, rects)

    q = np.array([[0.5, 0.2, 0.6, 0.3], [0.8, 0.5, 1.5, 3.5]])

    # Single query
    result = prtree.query(q[0])
    assert result == [1]

    # Batch query with 1D array (becomes batch of 1)
    result = prtree.batch_query(q[0])
    assert result == [[1]]


def test_insert_erase_example():
    """Test README insert/erase example.."""
    idxes = np.array([1, 2])
    rects = np.array([[0.0, 0.0, 1.0, 0.5], [1.0, 1.5, 1.2, 3.0]])
    prtree = PRTree2D(idxes, rects)

    # erase(delete) by index
    prtree.erase(1)  # delete the rectangle with idx=1 from the PRTree

    # insert a new one
    prtree.insert(3, np.array([0.3, 0.1, 0.5, 0.2]))  # add a new rectangle to the PRTree

    # Verify
    result = prtree.query([0.4, 0.15, 0.45, 0.18])
    assert 3 in result
    assert 1 not in result


def test_save_load_example(tmp_path):
    """Test README save/load example.."""
    idxes = np.array([1, 2])
    rects = np.array([[0.0, 0.0, 1.0, 0.5], [1.0, 1.5, 1.2, 3.0]])
    prtree = PRTree2D(idxes, rects)

    fname = tmp_path / "tree.bin"
    fname_str = str(fname)

    # save
    prtree.save(fname_str)

    # load with binary file
    prtree_loaded = PRTree2D(fname_str)
    assert prtree_loaded.size() == 2

    # or deferred load
    prtree2 = PRTree2D()
    prtree2.load(fname_str)
    assert prtree2.size() == 2

    # Verify queries match
    q = np.array([[0.5, 0.2, 0.6, 0.3]])
    result_original = prtree.batch_query(q)
    result_loaded1 = prtree_loaded.batch_query(q)
    result_loaded2 = prtree2.batch_query(q)

    assert result_original == result_loaded1 == result_loaded2
